set backspace=eol,start,indent
set number
syntax on
set tabstop=4
set mouse=a
set numberwidth=1
set title
set noerrorbells
set scrolloff=3
set foldmethod=indent
set foldlevel=99
set autoindent
set smartindent
set laststatus=2
set hlsearch
set incsearch
set shiftwidth=4
set softtabstop=4
